spring:
  profiles:
    active: ${ENV:local}

---
# Profile: local
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    open-in-view: false

logging:
  level:
    root: INFO
    com:
      quote: DEBUG

quotes:
  api:
    baseUrl: https://api.quotable.io/quotes
    path:
      randomQuotes: /random
    defaultPageSize: 20

resilience4j.retry:
  instances:
    extQuoteApi:
      maxAttempts: 3
      waitDuration: 1s

---
# Profile: production
spring:
  config:
    activate:
      on-profile: production

  datasource:
    url:
    driverClassName:
    username:
    password:

  jpa:
    open-in-view: false

quotes:
  api:
    baseUrl: https://api.quotable.io
    path:
      randomQuotes: /random
    defaultPageSize: 20

resilience4j.retry:
  instances:
    extQuoteApi:
      maxAttempts: 3
      waitDuration: 1s